// Offline editor controller checks. This is not browser visual acceptance.
const fs=require('node:fs'),vm=require('node:vm'),assert=require('node:assert/strict');
const html=fs.readFileSync('src/neutral_atom_app/visualization/qec_ordered_experiment.html','utf8');
const nodes=new Map([...html.matchAll(/id="([^"]+)"/g)].map(m=>[m[1],{value:'',innerHTML:'',textContent:'',hidden:false,disabled:false,showModal(){throw Error('Unexpected failure dialog');},close(){}}]));
nodes.get('rowFilter').value='active';nodes.get('gateMeta').value='{}';
const context=vm.createContext({document:{getElementById:id=>{assert(nodes.has(id),`missing ${id}`);return nodes.get(id);}},console,Map,Set,JSON});
const run=s=>vm.runInContext(s,context);
run(fs.readFileSync('src/neutral_atom_app/visualization/qec_editor.js','utf8'));
const main=html.split('<script>')[1].split('</script>')[0];
run(main.slice(0,main.indexOf('(async()=>')));
const input=JSON.parse(fs.readFileSync(process.argv[2]||'artifacts/qec-axis-hold/attempt1/qec_ghz2/input.json','utf8'));
run(`spec=${JSON.stringify(input)};render()`);
assert(nodes.get('page').textContent.includes('逻辑层'));
const original=run('JSON.stringify(spec.gates)');
run('selectGate(spec.gates[0].id)');
assert.equal(run('JSON.stringify(spec.gates)'),original,'selection must not delete');
nodes.get('saveGate').onclick();assert.equal(run('JSON.stringify(spec.gates)'),original,'no-op edit preserves gates');
run(`offset=logicalColumns(spec.gates)[spec.gates.findIndex(g=>g.id===spec.qec_protocol.stages.find(s=>s.stage==='logical-cnot').gate_id)];render()`);
assert(nodes.get('circuit').innerHTML.includes('Q000'));
const matches=[...nodes.get('circuit').innerHTML.matchAll(/aria-label="选择 ([^"]+)"/g)].map(m=>m[1]);
assert.equal(matches.filter(s=>s.includes(' CZ ')&&/Q00[0-8] Q0(09|1[0-7])/.test(s)).length,9);
run('selectGate(spec.gates.find(g=>g.condition?.length).id)');
const selected=run('JSON.stringify(spec.gates.find(g=>g.id===selectedGate))');nodes.get('saveGate').onclick();
assert.equal(run('JSON.stringify(spec.gates.find(g=>g.id===selectedGate))'),selected);
nodes.get('backend').value='row_column';nodes.get('backend').onchange();
nodes.get('router').value='axis_hold';nodes.get('router').onchange();
assert.equal(run('JSON.stringify(spec.gates)'),original,'backend/router change must not edit circuit');
nodes.get('readoutMode').value='slm_only';nodes.get('readoutK').value='2';nodes.get('readoutBudget').value='8';
nodes.get('readoutMode').onchange();
assert.equal(run('spec.readout_policy.mode'),'slm_only');
assert.equal(run('spec.readout_policy.top_k'),2);
assert.equal(run('JSON.stringify(spec.gates)'),original,'readout strategy must not edit circuit');
run("selectedGate=null;$('kind').value='CZ';$('qa').value='0';$('qb').value='1';$('gateMeta').value='{}'");
nodes.get('add').onclick();assert.equal(run('spec.gates.length'),input.gates.length+1);
assert.equal(run('spec.gates.at(-1).gate_type'),'CZ');
nodes.get('removeGate').onclick();assert.equal(run('JSON.stringify(spec.gates)'),original);
assert.equal(nodes.get('compile').disabled,false,'editing does not start compile');
console.log('PASS offline editor: layer paging, 9 transversal pairs, select/edit/append/delete, condition preservation, backend/router isolation');
