const fs=require('node:fs'),assert=require('node:assert/strict');
const harness=require('./viewer_harness.cjs');
const h=harness(fs.readFileSync(process.argv[2],'utf8')), {el,get}=h;
const original=get('JSON.stringify(data)'),duration=get('data.duration');
assert(!el('play').disabled);assert(el('playback-status').textContent.includes('已暂停'));
let prevented=false;
const wheel={clientX:200,clientY:200,deltaY:-100,preventDefault(){prevented=true;}};
el('canvas').listeners.wheel(wheel);assert(!prevented);assert.equal(get('view.zoom'),1);
el('canvas').listeners.wheel({...wheel,ctrlKey:true});assert(prevented);assert(get('view.zoom')>1);
el('seek-time').value=String(duration/3);el('seek-time-button').onclick();assert.equal(get('ui.time'),duration/3);assert(!get('ui.playing'));
el('seek-time').value=String(duration+1);el('seek-time-button').onclick();assert(el('seek-error').textContent);assert.equal(get('ui.time'),duration/3);
el('canvas').listeners.keydown({key:' ',preventDefault(){}});assert(get('ui.playing'));
el('canvas').listeners.keydown({key:' ',preventDefault(){}});assert(!get('ui.playing'));
el('canvas').listeners.keydown({key:'ArrowRight',preventDefault(){}});assert(get('ui.time')>duration/3);
const physical=get('JSON.stringify(current.atoms)');el('fit-atoms').onclick();assert.equal(get('JSON.stringify(current.atoms)'),physical);
el('fit').onclick();assert.equal(get('view.zoom'),1);assert.equal(get('view.panX'),0);
el('end').onclick();assert.equal(get('ui.time'),duration);assert(!get('ui.playing'));assert(el('playback-status').textContent.includes('已到终点'));
el('play').onclick();assert.equal(get('ui.time'),0);assert(get('ui.playing'));
assert.equal(get('JSON.stringify(data)'),original);
const empty=harness(fs.readFileSync(process.argv[3],'utf8'));
assert(empty.el('play').disabled);assert(empty.el('slider').disabled);assert(empty.el('seek-time').disabled);
assert(empty.el('operation-title').textContent.includes('静态布局'));assert(!empty.el('event').textContent.includes('完成'));
console.log('PASS replay controls, wheel intent, keyboard, validated seek, end/restart, fit and static preview; recording unchanged');
