/* View only: physical compilation, initial placement and timing stay in Python. */
'use strict';
const $=id=>document.getElementById(id), fields=['atom_count','source_rows','source_columns','spacing_um','aod_rows','aod_columns','evaluations','seed','compile_timeout_s','proposal_pool','workers'];
const esc=x=>String(x).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
let defaults,report,recordings={},viewer,mode='optimized',pulses=new Map(),gateElements=[],lastTime=-1;
function setInput(v){for(const f of fields)$(f).value=v[f]??({proposal_pool:64,workers:1})[f];$('terminal_mode').value=v.terminal_mode||'fixed';$('gates').value=JSON.stringify(v.gates,null,2);capacity();$('draft').textContent='仅手动编译';}
function getInput(){const value={};for(const f of fields)value[f]=Number($(f).value);value.terminal_mode=$('terminal_mode').value;value.gates=JSON.parse($('gates').value);return value;}
function capacity(){$('capacity').textContent=`可用 ${Number($('source_rows').value)*Number($('source_columns').value)} 个 SLM；AOD 容量 ${Number($('aod_rows').value)*Number($('aod_columns').value)} 个行列交点。`;}
function fail(message){$('failure-detail').textContent=message;$('failure').hidden=false;$('failure').focus();$('status').textContent='本次失败，详细信息已展开。';}
async function json(url,options){const r=await fetch(url,options);const v=await r.json();if(!r.ok)throw Error(v.error||'请求失败');return v;}
function board(id,mapping,color){const sites=report.source_sites,m=new Map(mapping.map(([q,s])=>[s,q]));const maxX=Math.max(...sites.map(s=>s.x_um)),maxY=Math.max(...sites.map(s=>s.y_um));const scale=400/Math.max(10,maxX,maxY),w=90+scale*maxX,h=90+scale*maxY;let svg=`<svg viewBox="0 0 ${w} ${h}" role="img" aria-label="${id==='baseline-board'?'顺序':'优化'}初态 SLM 格点及原子编号">`;
for(const x of new Set(sites.map(s=>s.x_um)))svg+=`<line x1="${45+x*scale}" y1="35" x2="${45+x*scale}" y2="${h-35}" stroke="#e4ebe6"/><text x="${45+x*scale}" y="20" text-anchor="middle" fill="#7a8c83" font-size="11">${x}</text>`;
for(const y of new Set(sites.map(s=>s.y_um)))svg+=`<line x1="35" y1="${45+y*scale}" x2="${w-35}" y2="${45+y*scale}" stroke="#e4ebe6"/><text x="15" y="${49+y*scale}" text-anchor="middle" fill="#7a8c83" font-size="11">${y}</text>`;
for(const s of sites){const q=m.get(s.id),x=45+s.x_um*scale,y=45+s.y_um*scale;svg+=`<g><title>${esc(s.id)} (${s.x_um}, ${s.y_um}) μm${q?' · '+esc(q):' · 空位'}</title><circle cx="${x}" cy="${y}" r="${q?7:5}" fill="${q?color:'white'}" stroke="${q?color:'#a7b4ad'}" ${q?'':'stroke-dasharray="2 2"'}/>${q?`<text x="${x}" y="${y+20}" text-anchor="middle" fill="${color}" font-size="10">${esc(q)}</text>`:''}</g>`;}
$(id).innerHTML=svg+'</svg>';const used=sites.filter(s=>m.has(s.id));return `${new Set(used.map(s=>s.y_um)).size} 个占据行 × ${new Set(used.map(s=>s.x_um)).size} 个占据列 · ${maxX} × ${maxY} μm 可用区域`;}
function drawCircuit(){const gates=report.input.gates,qs=Array.from({length:report.input.atom_count},(_,i)=>'Q'+String(i).padStart(3,'0'));const levels=new Map(qs.map(q=>[q,0])),byId=new Map(),busy=new Map();const glyphs=[];let max=0;
for(const g of gates){const targets=g.qubit_ids.map(q=>qs.indexOf(q)),deps=[...(g.depends_on||[]),...(g.condition||[]).map(c=>c[0])];let layer=Math.max(0,...g.qubit_ids.map(q=>levels.get(q)),...deps.map(d=>(byId.get(d)??-1)+1));const lo=Math.min(...targets),hi=Math.max(...targets);while((busy.get(layer)||[]).some(([a,b])=>lo<=b&&hi>=a))layer++;busy.set(layer,[...(busy.get(layer)||[]),[lo,hi]]);byId.set(g.id,layer);for(const q of g.qubit_ids)levels.set(q,layer+1);max=Math.max(max,layer);const x=110+76*layer,ys=targets.map(i=>42+45*i);let shapes=ys.length>1?`<line x1="${x}" x2="${x}" y1="${Math.min(...ys)}" y2="${Math.max(...ys)}" stroke="currentColor" stroke-width="2"/>`:'';for(const y of ys)shapes+=`<rect x="${x-23}" y="${y-14}" width="46" height="28" rx="6" fill="white" stroke="currentColor"/><text x="${x}" y="${y+4}" text-anchor="middle" font-size="${g.gate_type.length>4?8:11}">${esc(g.gate_type)}</text>`;glyphs.push(`<g class="gate" tabindex="0" role="button" data-gate="${esc(g.id)}" aria-label="${esc(g.id+' '+g.gate_type+' '+g.qubit_ids.join(','))}"><title>${esc(g.id+' '+g.gate_type+' '+g.qubit_ids.join(','))}</title>${shapes}<text class="gate-id" x="${x}" y="${Math.min(...ys)-20}" text-anchor="middle">${esc(g.id)}</text></g>`);}
const w=Math.max(660,160+max*76),h=75+qs.length*45;let wires=qs.map((q,i)=>`<text x="8" y="${46+45*i}" font-size="12">${q}</text><line x1="72" x2="${w-16}" y1="${42+45*i}" y2="${42+45*i}" stroke="#d4ddd7"/>`).join('');$('circuit').innerHTML=`<svg width="${w}" height="${h}" role="img" aria-label="完整编译输入电路">${wires}${glyphs.join('')}</svg>`;
gateElements=[...document.querySelectorAll('[data-gate]')];for(const el of gateElements){const seek=()=>{const p=pulses.get(el.dataset.gate);if(p)viewer.setTime((p.start+p.end)/2);};el.onclick=seek;el.onkeydown=e=>{if(e.key==='Enter'||e.key===' '){e.preventDefault();seek();}};}lastTime=-1;}
function choose(next){mode=next;if(viewer)viewer.destroy();const data=recordings[mode];viewer=NeutralAtomViewer.mount($('viewer'),data,{compact:true,gridStepUm:report.input.spacing_um,showCandidateSites:false,dashedEmptySlm:true,modelCaption:'有序行列 AOD · 正交真实轨迹 · 同类光门并行 · 完整初态/运输/门/结束状态回放'});pulses=new Map();for(const op of data.operations)if(['raman_rotation','entangling_pulse','measurement','reset'].includes(op.kind))for(const id of op.gate_ids||[])pulses.set(id,op);$('choose-baseline').setAttribute('aria-pressed',mode==='baseline');$('choose-optimized').setAttribute('aria-pressed',mode==='optimized');$('mode-label').textContent=(mode==='baseline'?'顺序排布':'优化布局')+' · '+data.duration.toFixed(2)+' μs';lastTime=-1;window.placementReplay={viewer,report,recordings,mode};}
async function show(id){const root='/'+encodeURIComponent(id)+'/';report=await json(root+'comparison.json');if(report.status!=='completed'){fail('没有有效的顺序基线与优化结果，不能展示为成功对照。\n'+JSON.stringify(report.trials,null,2));return;}
recordings={baseline:await json(root+'baseline.json'),optimized:await json(root+'optimized.json')};setInput(report.input);$('comparison').hidden=$('execution').hidden=false;$('result-label').textContent=`${report.input.atom_count} 原子 · ${report.input.gates.length} 个门/控制槽 · ${report.source_sites.length} 个可选 SLM · 本次 ${report.trials.length} 次候选评估`;
$('gain').textContent=report.improvement_percent>1e-8?`完整执行时间减少 ${report.improvement_percent.toFixed(2)}%`:'预算内没有更快的候选，保留顺序排布';$('baseline-shape').textContent=board('baseline-board',report.baseline.mapping,'#5364bc');$('optimized-shape').textContent=board('optimized-board',report.selected.mapping,'#18785e');
const a=report.baseline_metrics,b=report.optimized_metrics,rows=[[report.terminal_mode==='stable'?'完成时间 / μs（不含末尾归还）':'总时间 / μs（含共同终态）','simulation_time_us'],['逻辑门完成 / μs','logical_completion_elapsed_us'],['装载批次','aod_load_count'],['原子总路程 / μm','total_atom_distance_um'],['完成门数','completed_gate_count']];const fmt=v=>typeof v==='number'?(Number.isInteger(v)?v:v.toFixed(3)):'—';$('metrics').innerHTML=rows.map(([label,key])=>`<tr><td>${label}</td><td>${fmt(a[key])}</td><td>${fmt(b[key])}</td></tr>`).join('');const d=report.diagnostics;$('shape-proof').textContent=`已尝试改变占据形状的布局：${d.evaluated_changed_shape} 个；选中结果${d.selected_changed_shape?'改变了占据形状':'未改变占据形状'}。独立物理重放与${report.terminal_mode==='stable'?'合法稳定结束':'共同终态'}校验通过。`;$('completion-note').textContent=report.terminal_mode==='stable'?'本次不执行末尾原layout归还；两版可在不同合法位置结束。CZ批后回程仍完整计时。': '历史固定终态对照：末尾恢复顺序基线的位置与开关。';
$('trials').innerHTML=report.trials.map(t=>`<tr><td>${t.index===0?'顺序基线':t.index}</td><td>${esc(t.origin)}</td><td>${esc(t.valid?t.time_us.toFixed(3):t.failure)}</td></tr>`).join('');$('evidence').innerHTML=`<a href="${root}comparison.json" target="_blank">完整对照与失败记录</a><a href="${root}search/search.json" target="_blank">全部初态映射</a><a href="${root}input.json" target="_blank">编译输入</a>`;drawCircuit();choose('optimized');$('status').textContent=`对照已完成。搜索及录制墙钟 ${report.wall_seconds.toFixed(1)} 秒；仿真时间见下表。`;history.replaceState(null,'','/?job='+encodeURIComponent(id));}
function sync(){if(viewer&&report){const t=viewer.getStatus().time_us;if(t!==lastTime){lastTime=t;let done=0,active=[];for(const el of gateElements){const p=pulses.get(el.dataset.gate);let state='';if(p&&t>=p.end){state='complete';done++;}else if(p&&t>=p.start){state='active';active.push(el.dataset.gate);}el.setAttribute('class','gate '+state);}$('circuit-status').textContent=`${mode==='baseline'?'顺序':'优化'} · ${t.toFixed(3)} μs · 已完成 ${done}/${report.input.gates.length}${active.length?' · 正在作用 '+active.join('、'):''}`;}}requestAnimationFrame(sync);}sync();
for(const f of fields)$(f).oninput=()=>{capacity();$('draft').textContent='草稿已修改；下方仍为上次编译结果';};$('terminal_mode').onchange=()=>$('draft').textContent='结束条件已修改，请重新编译';$('gates').oninput=()=>$('draft').textContent='电路已修改，请手动重新编译';
$('choose-baseline').onclick=()=>choose('baseline');$('choose-optimized').onclick=()=>choose('optimized');$('at-initial').onclick=()=>viewer.setTime(0);$('at-final').onclick=()=>viewer.setTime(recordings[mode].duration);$('dismiss').onclick=()=>$('failure').hidden=true;$('example').onclick=()=>setInput(defaults);
$('download-input').onclick=()=>{try{const a=document.createElement('a');const url=URL.createObjectURL(new Blob([JSON.stringify(getInput(),null,2)],{type:'application/json'}));a.href=url;a.download='free-placement-input.json';a.click();URL.revokeObjectURL(url);}catch(e){fail(e.message);}};$('import-input').onclick=()=>$('input-file').click();$('input-file').onchange=async()=>{try{setInput(JSON.parse(await $('input-file').files[0].text()));}catch(e){fail(e.message);}};
$('compile').onclick=async()=>{try{$('failure').hidden=true;const value=getInput();$('compile').disabled=true;const job=await json('/api/compile',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(value)});$('status').textContent='正在编译顺序基线；每个候选均完整执行并独立重放。';const poll=async()=>{try{const state=await json('/api/jobs/'+job.id);const p=state.progress;$('status').textContent=typeof p==='string'?p:p.phase==='search'?`已评估 ${p.trial}/${p.budget} · ${p.valid?p.time_us.toFixed(3)+' μs':'该候选失败，记录原因后继续'} · 已耗时 ${p.wall_seconds.toFixed(1)} 秒`:p.message;if(state.status==='running'){setTimeout(poll,1000);return;}$('compile').disabled=false;if(state.status==='completed')await show(job.id);else fail(state.error||'本次没有完整有效结果。');}catch(e){$('compile').disabled=false;fail(e.message);}};poll();}catch(e){$('compile').disabled=false;fail(e.message);}};
async function init(){const data=await json('/api/info');defaults=data.defaults;setInput(defaults);for(const id of data.available){const a=document.createElement('a');a.href='/?job='+encodeURIComponent(id);a.textContent=({'default':'8 原子 · 固定伙伴对照','partners-12':'12 原子 · 84 门 · 多轮换伙伴','grid-16':'16 原子 · 96 门 · 历史固定终态','partners-12-parallel':'12 原子 · 并行搜索 · 不回原 layout','grid-16-parallel':'16 原子 · 并行搜索 · 不回原 layout'})[id]||id;a.onclick=e=>{e.preventDefault();show(id).catch(e=>fail(e.message));};$('existing').append(a);}const job=new URLSearchParams(location.search).get('job')||(['grid-16-parallel','partners-12-parallel','default'].find(id=>data.available.includes(id))||null);if(job)await show(job);else $('status').textContent='输入已就绪，点击线路下方按钮开始编译。';}init().catch(e=>fail(e.message));
