(()=>{'use strict';
const D=JSON.parse(document.getElementById('native-data').textContent),$=id=>document.getElementById(id),N=D.initial.length,O=D.ops,G=D.gates,STRIDE=512;
const canvas=$('scene'),ctx=canvas.getContext('2d'),names=['装载至 AOD','移动','卸载至 SLM','CZ 脉冲','H 单比特门'],qname=q=>'Q'+String(q).padStart(3,'0');
let xy=new Float64Array(D.initial.flat()),held=new Uint8Array(N),completed=0,cursor=0,playing=false,last=0,selected=0,page=0,lastCircuit=-1,camera=[200,195,1],width=900,height=540;
const checkpoints=[],cz=[],gatePrefixes=new Uint32Array(O.length+1),czPrefixes=new Uint32Array(O.length+1);
const nextGateAt=new Uint32Array(O.length+1);nextGateAt[O.length]=G.length-1;for(let i=O.length-1;i>=0;i--)nextGateAt[i]=O[i][3][0]??nextGateAt[i+1];
function apply(op,p=xy,h=held){if(op[0]===1){for(const [q,x,y]of op[2]){p[2*q]=x;p[2*q+1]=y}}else if(op[0]===0||op[0]===2){for(const q of op[2])h[q]=op[0]===0?1:0}}
for(let i=0;i<=O.length;i++){if(i%STRIDE===0)checkpoints.push([xy.slice(),held.slice()]);if(i===O.length)break;const op=O[i];if(op[0]===3)cz.push(i);gatePrefixes[i+1]=gatePrefixes[i]+op[3].length;czPrefixes[i+1]=czPrefixes[i]+(op[0]===3?1:0);apply(op)}
xy=checkpoints[0][0].slice();held=checkpoints[0][1].slice();
const sites=[];for(const zone of [...D.architecture.storage_zones,...D.architecture.entanglement_zones])for(const s of zone.slms)for(let r=0;r<s.r;r++)for(let c=0;c<s.c;c++)sites.push([s.location[0]+c*s.site_separation[0],s.location[1]+r*s.site_separation[1]]);
function bound(v,a,b){return Math.max(a,Math.min(b,v))}function world(x,y){return[(x-width/2)/camera[2]+camera[0],(y-height/2)/camera[2]+camera[1]]}function screen(x,y){return[(x-camera[0])*camera[2]+width/2,(y-camera[1])*camera[2]+height/2]}
function go(value,pause=true){if(pause)playing=false;cursor=bound(value,0,O.length);const target=Math.floor(cursor);if(target<completed||target-completed>STRIDE){const k=Math.floor(target/STRIDE),state=checkpoints[k];xy=state[0].slice();held=state[1].slice();completed=k*STRIDE}while(completed<target)apply(O[completed++]);draw();}
function fit(){camera=[200,195,Math.min((width-45)/430,(height-45)/445)];draw()}function ez(){camera=[200,354,Math.min((width-45)/430,(height-45)/125)];draw()}
function focus(){camera=[xy[selected*2],xy[selected*2+1],Math.max(5,camera[2])];draw()}
function locateCZ(n){const i=bound(Math.trunc(n),1,cz.length);$('cz-index').value=i;selected=O[cz[i-1]][2][0];$('atom-id').value=selected;$('gate-index').value=O[cz[i-1]][3][0]+1;go(cz[i-1]);page=Math.floor(O[cz[i-1]][3][0]/30)*30;lastCircuit=-1;draw()}
function circle(x,y,r,fill,stroke){ctx.beginPath();ctx.arc(x,y,r,0,Math.PI*2);if(fill){ctx.fillStyle=fill;ctx.fill()}if(stroke){ctx.strokeStyle=stroke;ctx.stroke()}}
function renderCircuit(){const op=O[completed],current=op?.[3]?.[0]??nextGateAt[completed];if(lastCircuit===page+':'+current+':'+completed)return;lastCircuit=page+':'+current+':'+completed;const stop=Math.min(G.length,page+30);$('gate-page').textContent=`${page+1}–${stop} / ${G.length} 个门`;
$('gate-rows').innerHTML=G.slice(page,stop).map(([kind,qs,index],j)=>`<tr class="${index===completed?'active':index<completed?'done':''}"><td>g${String(page+j).padStart(5,'0')}</td><td>${kind}</td><td>${qs.map(qname).join(' ↔ ')}</td><td>${index+1}</td><td><button data-gate="${page+j}">定位</button></td></tr>`).join('');
const start=bound(current-3,0,Math.max(0,G.length-9)),subset=G.slice(start,start+9),qubits=[...new Set(subset.flatMap(g=>g[1]))].sort((a,b)=>a-b),sw=900,sh=Math.max(130,qubits.length*30+30),sx=i=>100+i*82,sy=q=>25+qubits.indexOf(q)*30;
let svg=qubits.map(q=>`<text x="8" y="${sy(q)+4}" font-size="12" fill="#71838d">${qname(q)}</text><line x1="85" x2="885" y1="${sy(q)}" y2="${sy(q)}" stroke="#d4dddc"/>`).join('');subset.forEach(([kind,qs,index],i)=>{const x=sx(i),color=index===completed?'#d95360':'#14796f';if(qs.length===2)svg+=`<line x1="${x}" x2="${x}" y1="${sy(qs[0])}" y2="${sy(qs[1])}" stroke="${color}"/>`;for(const q of qs)svg+=`<rect x="${x-18}" y="${sy(q)-10}" width="36" height="20" rx="4" fill="white" stroke="${color}"/><text x="${x}" y="${sy(q)+4}" text-anchor="middle" font-size="11" fill="${color}">${kind}</text>`});$('circuit-svg').setAttribute('viewBox',`0 0 ${sw} ${sh}`);$('circuit-svg').innerHTML=svg;
}
function draw(){const op=O[completed],fraction=cursor-completed,positions=new Map(),active=new Set(op?(op[0]===1?op[2].map(m=>m[0]):op[2]):[]);if(op?.[0]===1&&$('interpolate').checked)for(const[q,x,y]of op[2])positions.set(q,[xy[2*q]+(x-xy[2*q])*fraction,xy[2*q+1]+(y-xy[2*q+1])*fraction]);const pos=q=>positions.get(q)||[xy[q*2],xy[q*2+1]];
if(playing&&$('follow').checked&&active.size){const q=active.values().next().value;[camera[0],camera[1]]=pos(q)}
ctx.clearRect(0,0,width,height);for(const z of [{lo:[0,0],hi:[400,288],color:'#eef3f5',name:'STORAGE / SZ'},{lo:[0,309],hi:[400,399],color:'#f0edf8',name:'ENTANGLEMENT / EZ'}]){const a=screen(...z.lo),b=screen(...z.hi);ctx.fillStyle=z.color;ctx.fillRect(a[0],a[1],b[0]-a[0],b[1]-a[1]);ctx.fillStyle='#71838d';ctx.font='11px system-ui';ctx.fillText(z.name,a[0]+5,a[1]+14)}
const tl=world(0,0),br=world(width,height),step=camera[2]>4?5:20;
if($('show-grid').checked){ctx.lineWidth=.5;ctx.strokeStyle='#dce3e8';ctx.font='10px system-ui';for(let x=Math.ceil(tl[0]/step)*step;x<br[0];x+=step){const p=screen(x,0);ctx.beginPath();ctx.moveTo(p[0],0);ctx.lineTo(p[0],height);ctx.stroke();ctx.fillStyle='#8a98a7';ctx.fillText(x+'',p[0]+2,height-5)}for(let y=Math.ceil(tl[1]/step)*step;y<br[1];y+=step){const p=screen(0,y);ctx.beginPath();ctx.moveTo(0,p[1]);ctx.lineTo(width,p[1]);ctx.stroke();ctx.fillText(y+'',3,p[1]-2)}}
const radius=bound(camera[2]*.75,1.5,5);if($('show-slm').checked){ctx.lineWidth=.6;ctx.setLineDash([2,2]);for(const[x,y]of sites){const p=screen(x,y);if(p[0]<-8||p[0]>width+8||p[1]<-8||p[1]>height+8)continue;circle(...p,radius+1,null,'#a5b4c6')}ctx.setLineDash([])}
if(op?.[0]===1){ctx.strokeStyle='#e89438';ctx.lineWidth=1.5;ctx.setLineDash([4,4]);for(const[q,x,y]of op[2]){const a=screen(xy[q*2],xy[q*2+1]),b=screen(x,y);ctx.beginPath();ctx.moveTo(...a);ctx.lineTo(...b);ctx.stroke()}ctx.setLineDash([])}
if(op?.[0]===3){ctx.strokeStyle='#d95360';ctx.lineWidth=3;for(let i=0;i<op[2].length;i+=2){ctx.beginPath();ctx.moveTo(...screen(...pos(op[2][i])));ctx.lineTo(...screen(...pos(op[2][i+1])));ctx.stroke()}}
for(let q=0;q<N;q++){const p=screen(...pos(q));if(p[0]<-10||p[0]>width+10||p[1]<-10||p[1]>height+10)continue;const color=active.has(q)&&op?.[0]>=3?'#d95360':active.has(q)&&op?.[0]===1?'#e89438':'#5364bc';if(held[q]){circle(...p,radius+2,null,'#e89438');ctx.fillStyle=color;ctx.beginPath();ctx.moveTo(p[0],p[1]-radius);ctx.lineTo(p[0]+radius,p[1]);ctx.lineTo(p[0],p[1]+radius);ctx.lineTo(p[0]-radius,p[1]);ctx.closePath();ctx.fill()}else circle(...p,radius,color);if(q===selected){circle(...p,radius+4,null,'#14796f');ctx.fillStyle='#14796f';ctx.font='12px system-ui';ctx.fillText(qname(q),p[0]+9,p[1]-8)}}
$('play').textContent=playing?'暂停':'播放';$('timeline').value=completed;$('progress').textContent=`已完成指令 ${completed.toLocaleString()} / ${O.length.toLocaleString()} · ${(100*cursor/O.length).toFixed(1)}% · 展示进度，非物理时间`;
$('operation').textContent=op?`${names[op[0]]} · 指令 ${completed+1}`:'全部原生指令已结束';$('operation-detail').textContent=op?`NAViz 源码第 ${op[1]} 行 · ${[...active].slice(0,4).map(qname).join(' ↔ ')}${active.size>4?' 等 '+active.size+' 个原子':''}`:'全部原子已卸载至 SZ。';$('counters').textContent=`完成线路门 ${gatePrefixes[completed]} / ${G.length}\n完成 CZ 层 ${czPrefixes[completed]} / ${cz.length}\nAOD 承载原子 ${held.reduce((a,b)=>a+b,0)}`;
const p=pos(selected);$('atom-detail').textContent=`${qname(selected)}\nx = ${p[0].toFixed(3)} μm\ny = ${p[1].toFixed(3)} μm\n承载：${held[selected]?'AOD（已装载）':'SLM'}\n当前：${active.has(selected)&&op?names[op[0]]:'空闲'}${positions.has(selected)?'\n位置为端点插值示意':''}`;renderCircuit();
}
$('timeline').max=O.length;$('timeline').oninput=e=>go(Number(e.target.value));$('play').onclick=()=>{if(cursor>=O.length)go(0);playing=!playing;last=0;draw()};$('prev').onclick=()=>go(Math.ceil(cursor)-1);$('next').onclick=()=>go(Math.floor(cursor)+1);$('start').onclick=()=>go(0);$('end').onclick=()=>go(O.length);
$('cz-go').onclick=()=>locateCZ(Number($('cz-index').value)||1);$('cz-prev').onclick=()=>locateCZ(Math.max(1,czPrefixes[completed]));$('cz-next').onclick=()=>locateCZ(czPrefixes[completed]+(opIsCZ()?2:1));function opIsCZ(){return O[completed]?.[0]===3}
$('fit').onclick=fit;$('ez').onclick=ez;$('zoom-in').onclick=()=>{camera[2]=bound(camera[2]*1.5,.3,40);draw()};$('zoom-out').onclick=()=>{camera[2]=bound(camera[2]/1.5,.3,40);draw()};
function pick(){selected=bound(Math.trunc(Number($('atom-id').value)||0),0,N-1);$('atom-id').value=selected;draw()};$('atom-go').onclick=pick;$('atom-focus').onclick=()=>{pick();focus()};
function gateGo(i){i=bound(Math.trunc(i),0,G.length-1);page=Math.floor(i/30)*30;$('gate-index').value=i+1;lastCircuit=-1;go(G[i][2]);selected=G[i][1][0];$('atom-id').value=selected;draw()}
$('gate-go').onclick=()=>gateGo(Number($('gate-index').value)-1);$('gate-rows').onclick=e=>{const b=e.target.closest('[data-gate]');if(b)gateGo(Number(b.dataset.gate))};$('gates-prev').onclick=()=>{page=Math.max(0,page-30);lastCircuit=-1;draw()};$('gates-next').onclick=()=>{page=Math.min(Math.floor((G.length-1)/30)*30,page+30);lastCircuit=-1;draw()};
for(const id of ['show-slm','show-grid','interpolate','follow'])$(id).onchange=draw;
let drag=null;canvas.onpointerdown=e=>{canvas.focus();drag=[e.offsetX,e.offsetY,...camera];canvas.setPointerCapture(e.pointerId)};canvas.onpointermove=e=>{if(drag){camera[0]=drag[2]-(e.offsetX-drag[0])/camera[2];camera[1]=drag[3]-(e.offsetY-drag[1])/camera[2];draw()}};canvas.onpointerup=e=>{if(drag&&Math.hypot(e.offsetX-drag[0],e.offsetY-drag[1])<4){let closest=14;for(let q=0;q<N;q++){const p=screen(xy[q*2],xy[q*2+1]),d=Math.hypot(p[0]-e.offsetX,p[1]-e.offsetY);if(d<closest){closest=d;selected=q}}$('atom-id').value=selected}drag=null;draw()};canvas.onwheel=e=>{if(!e.ctrlKey&&!e.metaKey)return;e.preventDefault();const before=world(e.offsetX,e.offsetY);camera[2]=bound(camera[2]*Math.exp(-e.deltaY*.002),.3,40);const after=world(e.offsetX,e.offsetY);camera[0]+=before[0]-after[0];camera[1]+=before[1]-after[1];draw()};canvas.onkeydown=e=>{if(e.code==='Space'){e.preventDefault();$('play').click()}if(e.code==='ArrowRight')$('next').click();if(e.code==='ArrowLeft')$('prev').click()};
new ResizeObserver(()=>{const r=canvas.getBoundingClientRect(),first=width===900;width=r.width;height=r.height;const d=devicePixelRatio||1;canvas.width=width*d;canvas.height=height*d;ctx.setTransform(d,0,0,d,0,0);if(first)fit();else draw()}).observe(canvas);
function tick(now){if(playing){if(last){const advance=Math.min(100,now-last)/1000*100*Number($('speed').value);go(cursor+advance,false);if(cursor>=O.length){playing=false;draw()}}last=now}else last=0;requestAnimationFrame(tick)}requestAnimationFrame(tick);
window.NativeInspector={seek:go,getState:()=>({completed,cursor,playing,selected,positions:Array.from(xy),held:Array.from(held),completedGates:gatePrefixes[completed],completedCZ:czPrefixes[completed]}),czIndices:cz};
fit();go(0);
})();
